"""Pinned external ComfyUI and H3/Context Loop contracts."""

from .camera import (
    ANIME_EMOTIONAL_FACE_PERFORMANCE_CUT_CAMERA,
    ANIME_EMOTIONAL_FACE_PERFORMANCE_CUT_CAMERA_H3,
    FACE_PERFORMANCE_CUT_ACTION,
    FACE_PERFORMANCE_CUT_ACTION_H3,
    FACE_PERFORMANCE_CUT_CAMERA,
    FACE_PERFORMANCE_CUT_CAMERA_H3,
)
from .environment_reference import (
    build_environment_definition,
    build_environment_retention,
)
from .context_loop_0_6_9 import (
    COMFYUI_BASELINE_COMMIT,
    COMFYUI_BASELINE_VERSION,
    CONTEXT_LOOP_0_6_9,
    CONTEXT_LOOP_BASELINE_COMMIT,
    CONTEXT_LOOP_BASELINE_VERSION,
    CONTRACT_ID,
    ContextLoopContract,
)
from .timing import DEFAULT_H3_TIMING_PROFILE, H3TimingProfile, TIMING_SCHEMA

__all__ = [
    "COMFYUI_BASELINE_COMMIT",
    "COMFYUI_BASELINE_VERSION",
    "CONTRACT_ID",
    "CONTEXT_LOOP_0_6_9",
    "CONTEXT_LOOP_BASELINE_COMMIT",
    "CONTEXT_LOOP_BASELINE_VERSION",
    "ContextLoopContract",
    "DEFAULT_H3_TIMING_PROFILE",
    "ANIME_EMOTIONAL_FACE_PERFORMANCE_CUT_CAMERA",
    "ANIME_EMOTIONAL_FACE_PERFORMANCE_CUT_CAMERA_H3",
    "FACE_PERFORMANCE_CUT_ACTION",
    "FACE_PERFORMANCE_CUT_ACTION_H3",
    "FACE_PERFORMANCE_CUT_CAMERA",
    "FACE_PERFORMANCE_CUT_CAMERA_H3",
    "H3TimingProfile",
    "build_environment_definition",
    "build_environment_retention",
    "TIMING_SCHEMA",
]
