param(
    [Parameter(Mandatory = $true)]
    [string]$OutputRoot
)

$resolved = (Resolve-Path -LiteralPath $OutputRoot -ErrorAction Stop).Path
if (-not (Get-Item -LiteralPath $resolved).PSIsContainer) {
    throw "OutputRoot must be a directory: $resolved"
}
$indexPath = Join-Path $resolved '_INDEX.md'
$marker = '<!-- generated by tools/index_comfyui_output.ps1; do not edit -->'
if (Test-Path -LiteralPath $indexPath) {
    $firstLine = Get-Content -LiteralPath $indexPath -TotalCount 1
    if ($firstLine -ne $marker) {
        throw "Refusing to overwrite an unmanaged index: $indexPath"
    }
}

function Get-Category([string]$relative) {
    if ($relative -match '^h3_chains/mv_director_') { return '完成動画・通常生成' }
    if ($relative -match '^h3_chains/shotlink-body-full') { return '研究用全編動画' }
    if ($relative -match '^h3_chains/(audio_ref_|shotlink-body-scene)') { return '短区間比較' }
    if ($relative -match '^mv_director(?:-\d+)?$') { return 'Plan・EMD・歌詞' }
    return '未分類・要確認'
}

function Get-Entry([string]$path, [string]$relative) {
    $files = @(Get-ChildItem -LiteralPath $path -File -Recurse -ErrorAction SilentlyContinue)
    $bytes = ($files | Measure-Object -Property Length -Sum).Sum
    if ($null -eq $bytes) { $bytes = 0 }
    $newest = $files | Sort-Object LastWriteTime -Descending | Select-Object -First 1
    return [pscustomobject]@{
        Category = Get-Category $relative
        Relative = $relative
        Files = $files.Count
        MiB = [math]::Round($bytes / 1MB, 0)
        Updated = if ($newest) { $newest.LastWriteTime.ToString('yyyy-MM-dd HH:mm') } else { '-' }
    }
}

$entries = [System.Collections.Generic.List[object]]::new()
foreach ($directory in (Get-ChildItem -LiteralPath $resolved -Directory | Sort-Object Name)) {
    if ($directory.Name -eq 'h3_chains') {
        foreach ($child in (Get-ChildItem -LiteralPath $directory.FullName -Directory | Sort-Object Name)) {
            $relative = "h3_chains/$($child.Name)"
            $entries.Add((Get-Entry $child.FullName $relative))
        }
    } else {
        $entries.Add((Get-Entry $directory.FullName $directory.Name))
    }
}

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add($marker)
$lines.Add('# ComfyUI output 索引')
$lines.Add('')
$lines.Add("生成日時: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')")
$lines.Add("対象: $resolved")
$lines.Add('')
$lines.Add('この索引は読み取り集計のスナップショットです。フォルダの移動・削除は行いません。生成中のフォルダは容量が変化します。外部のWFやレポートによる絶対パス参照は、この索引だけでは検出できません。')
$lines.Add('')
foreach ($category in @('完成動画・通常生成', '研究用全編動画', '短区間比較', 'Plan・EMD・歌詞', '未分類・要確認')) {
    $group = @($entries | Where-Object Category -eq $category | Sort-Object Relative)
    if (-not $group.Count) { continue }
    $lines.Add("## $category")
    $lines.Add('')
    $lines.Add('| フォルダ | ファイル数 | 概算 MiB | 最終更新 |')
    $lines.Add('| --- | ---: | ---: | --- |')
    foreach ($entry in $group) {
        $lines.Add("| [$($entry.Relative)](<$($entry.Relative)/>) | $($entry.Files) | $($entry.MiB) | $($entry.Updated) |")
    }
    $lines.Add('')
}
$totalMiB = ($entries | Measure-Object -Property MiB -Sum).Sum
$lines.Add("計: $($entries.Count) フォルダ、概算 $totalMiB MiB。")
$lines.Add('')
$lines.Add('移動する場合は、生成キューが空であること、外部参照の有無、完成動画と再開用checkpointの保持方針を別途確認してください。')
Set-Content -LiteralPath $indexPath -Value $lines -Encoding utf8
Write-Output "index=$indexPath folders=$($entries.Count) approx_mib=$totalMiB"
